apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: todo-flaskapp
  name: todo-flaskapp
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30002	
  selector:
    io.kompose.service: todo-flaskapp
